"""The Lenovo case dashboard (frontend/lenovo.html) must show the current production figures (FE-009).

frontend/data/eroi-data.js is generated by frontend/scripts/build_eroi_data.py; these tests fail
when it is stale against the manifests it was built from. Rebuild with:

    python frontend/scripts/build_eroi_data.py
"""

import json
import re
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
E = ROOT / "data/curated/experimental"


def _eroi() -> dict:
    text = (ROOT / "frontend/data/eroi-data.js").read_text(encoding="utf-8")
    return json.loads(text[text.index("{"): text.rindex("}") + 1])


def _manifest(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_dashboard_shows_the_current_fifa_specific_estimate_and_total_effect():
    d = _eroi()
    fs = _manifest(E / "sponsorship_exposure_timing_v1/exposure_timing_manifest.json")["fifa_specific_effect"]
    head = _manifest(E / "sponsorship_total_effect_v1/estimate_manifest.json")
    shown = d["exposure"]["fifaSpecific"]
    assert np.isclose(shown["primary_index_points"], fs["primary_index_points"])
    assert np.allclose(shown["statistical_band_95_uplift_pct"], fs["statistical_band_95_uplift_pct"])
    assert np.isclose(shown["attribution_band_upper_index_points"], fs["attribution_band_upper_index_points"])
    assert np.isclose(d["exposure"]["total"]["lift"], head["total_effect"]["lift_index_points"], atol=1e-3)
    assert np.isclose(d["exposure"]["design"]["placeboP"], head["primary"]["p_value"], atol=1e-3)


def test_dashboard_brand_values_match_the_valuation_manifest():
    d = _eroi()
    # ADR-0045: every money figure on the dashboard comes from the income split (brand_value_dcf_v2).
    dcf = _manifest(E / "brand_value_dcf_v2/brand_value_dcf_manifest.json")["primary_result"]
    assert np.isclose(d["evaluation"]["dcf"]["brandValue"], dcf["brand_value_usd_m"] * 1e6, rtol=1e-6)
    for case, key in {"conservative": "statistical_band_95_low", "base": "primary", "ambitious": "attribution_band_upper"}.items():
        assert np.isclose(d["monetization"]["scenarios"][case]["value"], dcf["fifa_added_brand_value_usd_m"][key] * 1e6, rtol=1e-6)
    # The value bridge ends at the FIFA-specific value and starts from the whole gap.
    bridge = d["monetization"]["bridge"]
    assert len(bridge) == 3  # FE-014: everything not attributed to FIFA is one aggregate step
    assert np.isclose(bridge[0]["value"] + bridge[1]["value"], bridge[2]["value"], rtol=1e-4, atol=1)


def test_dashboard_uses_no_simulated_data_or_monetary_media_value():
    js = (ROOT / "frontend/js/eroi.js").read_text(encoding="utf-8")
    html = (ROOT / "frontend/lenovo.html").read_text(encoding="utf-8")
    assert "data/eroi-data.js" in html and not re.search(r"demo-data|real-data", html)
    assert "industry_claimed_media_value" not in js   # P1: media value is never shown as money
    assert not (ROOT / "frontend/data/demo-data.js").exists()
    # ADR-0044: the dashboard shows only the Lenovo-specific brand measure.
    data = (ROOT / "frontend/data/eroi-data.js").read_text(encoding="utf-8")
    assert "literal" not in js.lower() and "literal" not in data.lower()
    # ADR-0045: no value from another route (market-cap reading, external valuations, comparison routes).
    for word in ("brand finance", "interbrand", "brandfinance", "marketcap", "royalty", "routes", "earningsperpoint"):
        assert word not in js.lower() and word not in data.lower(), word
    d = _eroi()
    assert "dcf" in d["evaluation"] and "brand" not in d["evaluation"]
