"""The Lenovo case dashboard (frontend/lenovo.html) must show the current production figures (FE-009).

frontend/data/eroi-data.js is generated by frontend/scripts/build_eroi_data.py; these tests fail
when it is stale against the manifests it was built from. Rebuild with:

    python frontend/scripts/build_eroi_data.py
"""

import json
import re
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
E = ROOT / "data/curated/experimental"


def _eroi() -> dict:
    text = (ROOT / "frontend/data/eroi-data.js").read_text(encoding="utf-8")
    return json.loads(text[text.index("{"): text.rindex("}") + 1])


def _manifest(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_dashboard_shows_the_current_fifa_specific_estimate_and_total_effect():
    d = _eroi()
    fs = _manifest(E / "sponsorship_exposure_timing_v1/exposure_timing_manifest.json")["fifa_specific_effect"]
    head = _manifest(E / "sponsorship_total_effect_v1/estimate_manifest.json")
    shown = d["exposure"]["fifaSpecific"]
    assert np.isclose(shown["primary_index_points"], fs["primary_index_points"])
    assert np.allclose(shown["statistical_band_95_uplift_pct"], fs["statistical_band_95_uplift_pct"])
    assert np.isclose(shown["attribution_band_upper_index_points"], fs["attribution_band_upper_index_points"])
    assert np.isclose(d["exposure"]["total"]["lift"], head["total_effect"]["lift_index_points"], atol=1e-3)
    assert np.isclose(d["exposure"]["design"]["placeboP"], head["primary"]["p_value"], atol=1e-3)


def test_dashboard_brand_values_match_the_valuation_manifest():
    d = _eroi()
    dom = _manifest(E / "brand_value_dominance_v1/brand_value_dominance_manifest.json")
    assert np.isclose(d["evaluation"]["brand"]["brandValue"], dom["values"]["brand_value_usd_m"] * 1e6, rtol=1e-6)
    fsv = dom["fifa_specific_incremental_brand_value"]["incremental_brand_value_usd_m"]
    assert np.isclose(d["monetization"]["scenarios"]["base"]["value"], fsv["primary"] * 1e6, rtol=1e-6)
    # The value bridge ends at the FIFA-specific value and starts from the whole gap.
    bridge = d["monetization"]["bridge"]
    assert np.isclose(sum(step["value"] for step in bridge[1:3]) + bridge[0]["value"], bridge[3]["value"], rtol=1e-4)


def test_dashboard_uses_no_simulated_data_or_monetary_media_value():
    js = (ROOT / "frontend/js/eroi.js").read_text(encoding="utf-8")
    html = (ROOT / "frontend/lenovo.html").read_text(encoding="utf-8")
    assert "data/eroi-data.js" in html and not re.search(r"demo-data|real-data", html)
    assert "industry_claimed_media_value" not in js   # P1: media value is never shown as money
    assert not (ROOT / "frontend/data/demo-data.js").exists()
    # ADR-0044: the dashboard shows only the Lenovo-specific brand measure.
    data = (ROOT / "frontend/data/eroi-data.js").read_text(encoding="utf-8")
    assert "literal" not in js.lower() and "literal" not in data.lower()
