"""The Lenovo case dashboard (frontend/lenovo.html) must show the current production figures (FE-009).

frontend/data/eroi-data.js is generated by frontend/scripts/build_eroi_data.py; these tests fail
when it is stale against the manifests it was built from. Rebuild with:

    python frontend/scripts/build_eroi_data.py
"""

import json
import re
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
E = ROOT / "data/curated/experimental"


def _eroi() -> dict:
    text = (ROOT / "frontend/data/eroi-data.js").read_text(encoding="utf-8")
    return json.loads(text[text.index("{"): text.rindex("}") + 1])


def _manifest(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_dashboard_shows_the_current_fifa_specific_estimate_and_total_effect():
    d = _eroi()
    fs = _manifest(E / "sponsorship_exposure_timing_v1/exposure_timing_manifest.json")["fifa_specific_effect"]
    head = _manifest(E / "sponsorship_total_effect_v1/estimate_manifest.json")
    shown = d["exposure"]["fifaSpecific"]
    assert np.isclose(shown["primary_index_points"], fs["primary_index_points"])
    assert np.allclose(shown["statistical_band_95_uplift_pct"], fs["statistical_band_95_uplift_pct"])
    assert np.isclose(shown["attribution_band_upper_index_points"], fs["attribution_band_upper_index_points"])
    assert np.isclose(d["exposure"]["total"]["lift"], head["total_effect"]["lift_index_points"], atol=1e-3)
    assert np.isclose(d["exposure"]["design"]["placeboP"], head["primary"]["p_value"], atol=1e-3)


def test_dashboard_brand_values_match_the_valuation_manifest():
    d = _eroi()
    # ADR-0045: every money figure on the dashboard comes from the income split (brand_value_dcf_v2).
    dcf = _manifest(E / "brand_value_dcf_v2/brand_value_dcf_manifest.json")["primary_result"]
    assert np.isclose(d["evaluation"]["dcf"]["brandValue"], dcf["brand_value_usd_m"] * 1e6, rtol=1e-6)
    for case, key in {"conservative": "statistical_band_95_low", "base": "primary", "ambitious": "attribution_band_upper"}.items():
        assert np.isclose(d["monetization"]["scenarios"][case]["value"], dcf["fifa_added_brand_value_usd_m"][key] * 1e6, rtol=1e-6)
    # The value bridge ends at the FIFA-specific value and starts from the whole gap.
    bridge = d["monetization"]["bridge"]
    assert len(bridge) == 3  # FE-014: everything not attributed to FIFA is one aggregate step
    assert np.isclose(bridge[0]["value"] + bridge[1]["value"], bridge[2]["value"], rtol=1e-4, atol=1)


def test_dashboard_uses_no_simulated_data_or_monetary_media_value():
    js = (ROOT / "frontend/js/eroi.js").read_text(encoding="utf-8")
    html = (ROOT / "frontend/lenovo.html").read_text(encoding="utf-8")
    assert "data/eroi-data.js" in html and not re.search(r"demo-data|real-data", html)
    assert "industry_claimed_media_value" not in js   # P1: media value is never shown as money
    assert not (ROOT / "frontend/data/demo-data.js").exists()
    # ADR-0044: the dashboard shows only the Lenovo-specific brand measure.
    data = (ROOT / "frontend/data/eroi-data.js").read_text(encoding="utf-8")
    assert "literal" not in js.lower() and "literal" not in data.lower()
    # ADR-0045: no value from another route (market-cap reading, external valuations, comparison routes).
    for word in ("brand finance", "interbrand", "brandfinance", "marketcap", "royalty", "routes", "earningsperpoint"):
        assert word not in js.lower() and word not in data.lower(), word
    d = _eroi()
    assert "dcf" in d["evaluation"] and "brand" not in d["evaluation"]


def test_method_pages_show_the_current_brand_index_and_design_choice():
    # FE-016: the in-depth Method pages read the Brand Index model and the twin's design selection.
    m = _eroi()["method"]
    bi = _manifest(ROOT / "data/curated/index/brand_index_manifest.json")
    assert np.isclose(m["brandIndex"]["phi"], bi["phi"], atol=1e-3)
    assert [s["admitted"] for s in m["brandIndex"]["screen"]].count(True) == len(bi["validity_screen"]["admitted"])
    selected = [d for d in m["designs"] if d["selected"]]
    assert len(selected) == 1 and selected[0]["oosRmspe"] == min(d["oosRmspe"] for d in m["designs"])


def test_television_page_shows_the_current_tv_check():
    # FE-019 / ADR-0046: the "why no television" page reads tv_exposure_check_v1, relative units only.
    tv = _eroi()["method"]["tv"]
    m = _manifest(E / "tv_exposure_check_v1/tv_exposure_check_manifest.json")
    assert m["monetary_totals_used"] is False
    assert np.allclose(tv["range"], m["summary"]["fifa_total_with_tv_range"], atol=0.01)
    assert np.isclose(tv["maxChange"], m["summary"]["max_change_vs_primary_index_points"], atol=0.01)
    assert len(tv["scenarios"]) == len(m["scenarios"])
